### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by xiaonan12138** [GAP-LAB-CUHK-SZ/REC-MV#14]
Dear author, I have read your latest updated data processing methods, but I still can't find some of them in the project. Could you please provide them again? Thank you very much!

**Comment by Zevrap-81** [comment]
Yes same here. In particular, how to generate the “fl_init/init_trans_matrix.pth” file. Please give some instructions on this!

**Comment by lingtengqiu** [comment]
> Dear author, I have read your latest updated data processing methods, but I still can't find some of them in the project. Could you please provide them again? Thank you very much!

I will upload ASAP

**Comment by lingtengqiu** [comment]
> Yes same here. In particular, how to generate the “fl_init/init_trans_matrix.pth” file. Please give some instructions on this!

When u run my code, the code first is going to optimize the initial fl trans.  you can delete init_trans_matrix.pth, next runing my code to try it.

**Comment by xiaonan12138** [comment]
Can you share these files first(generate_boxs.py，generate_normals.py，prcess_data_all.py，get_reconstructed_poses.py，get_smpl_rec_camera.py), my love friend, I am currently doing a comparison experiment, if you can help me I would be very grateful!

**Comment by lingtengqiu** [comment]
> Can you share these files first(generate_boxs.py，generate_normals.py，prcess_data_all.py，get_reconstructed_poses.py，get_smpl_rec_camera.py), my love friend, I am currently doing a comparison experiment, if you can help me I would be very grateful!

Hi, we build the huggingface model to help ones to obtain their videos' training data. 
see in [huggingface](https://huggingface.co/mambazjp/REC-MV_preprocess/tree/main)
Good luck for your works.
