### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by xiaonan12138** [GAP-LAB-CUHK-SZ/REC-MV#16]
I have a question，My tcmr output .pkl only 9 items, but your tcmr output have 11 items，my output not
 have gt_joints2d, Where did gt_joints2d come from?

**Comment by lingtengqiu** [comment]
gt_joints2d obtained from Open-Pose

**Comment by xiaonan12138** [comment]
There is no way to get the pkl file that can be used, and the pkl generated directly with tcmr seems to be unable to be used directly.

**Comment by xiaonan12138** [comment]
Dear author, I have a few more questions first about the pkl file that tcmr processed in which gt_joints2d has 17 key points, not 18, which is missing. For the second question, how should mask2fl be obtained? I follow the readme you provided to do it in parsing_mask_to_fl.py, which requires json_hand_label_no_bottom_curve. How can I get this folder? I am very eager to know the answers to these questions. If possible, we can contact each other via email or WeChat. I would be honored if you could help me!

**Comment by lingtengqiu** [comment]
> Dear author, I have a few more questions first about the pkl file that tcmr processed in which gt_joints2d has 17 key points, not 18, which is missing. For the second question, how should mask2fl be obtained? I follow the readme you provided to do it in parsing_mask_to_fl.py, which requires json_hand_label_no_bottom_curve. How can I get this folder? I am very eager to know the answers to these questions. If possible, we can contact each other via email or WeChat. I would be honored if you could help me!

we can concat with each other via email(220019047@link.cuhk.edu.cn)
