### ISSUE TITLE
could you please tell me how i can get permission to this link

### ISSUE THREAD

**Issue by msverma101** [GAP-LAB-CUHK-SZ/REC-MV#17]
could you please tell me how i can get permission to this link

> Hi, Mingi.
> 
> The Female1, Female3, Male1, Male2 are the synthetic dataset produced by SelfRecon. For Female 3(casual, sport), Male 1(casual, plaza, sport), and Male 2(causal, outdoor, plaza, sport), there are the items from People Snapshot. You could obtain their Synthetic data from the following [link](https://mailustceducn-my.sharepoint.com/personal/jby1993_mail_ustc_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjby1993%5Fmail%5Fustc%5Fedu%5Fcn%2FDocuments%2FSelfReconData&ga=1)

**Comment by msverma101** [comment]
hello could you please tell me how i can access to this link

**Comment by lingtengqiu** [comment]
see [link](https://mailustceducn-my.sharepoint.com/personal/jby1993_mail_ustc_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjby1993%5Fmail%5Fustc%5Fedu%5Fcn%2FDocuments%2FSelfReconData&ga=1), or you can download from [SelfRecon](https://github.com/jby1993/SelfReconCode)
