### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by wishinghao** [GAP-LAB-CUHK-SZ/REC-MV#20]
Hello, I trained the "anran" example and found that the training is very slow (it hasn't finished after 5 days), significantly slower compared to Selfrecon (which took about two days). How long should the training time approximately be, and is there a mistake in my settings? I used one V100.

**Comment by lingtengqiu** [comment]
you can modify epoch in configs files. In my setting, single 3090, epoch =160, it spends 16-20 hours in training one case.
