### ISSUE TITLE
Demo problem

### ISSUE THREAD

**Issue by karaokenoway** [GAP-LAB-CUHK-SZ/REC-MV#21]
When i run the demo code  `bash ./scripts/large_pose/test_large_pose_A_fl.sh 0 anran_tic anran_tic_self_rotated`, there is something wrong with the file. 
returns the error:
` File "infer_fl.py", line 223, in <module>
    colors_list, imgs_list, def1imgs_list, defVs_list, smpl_list, merge_imgs = optNet.infer_garment(garment_TmpVs,`
` File "/home/wo/Code/Github/REC-MV-main/engineer/networks/OptimGarmentNetwork.py", line 2960, in infer_garment
    save_ply(os.path.join('fl_debug', '{:05}.ply'.format(fl_idx)), fl.view(-1,3).detach().cpu())
`
`File "/home/wo/anaconda3/envs/REC-MV/lib/python3.8/site-packages/pytorch3d/io/ply_io.py", line 1357, in save_ply
    with _open_file(f, path_manager, "wb") as f:
`
`File "/home/wo/anaconda3/envs/REC-MV/lib/python3.8/site-packages/pytorch3d/io/utils.py", line 26, in _open_file
    f = path_manager.open(f, mode)
`
` File "/home/wo/anaconda3/envs/REC-MV/lib/python3.8/site-packages/iopath-0.1.10-py3.8.egg/iopath/common/file_io.py", line 645, in _open
FileNotFoundError: [Errno 2] No such file or directory: 'fl_debug/00000.ply'
`
what should i do?

**Comment by lingtengqiu** [comment]
I guess you do not build fl_debug folder? The code line  ``save_ply(os.path.join('fl_debug', '{:05}.ply'.format(fl_idx)), fl.view(-1,3).detach().cpu())`` is utilized to visualize featureline position. If you do not want to save it, you can annotate this code
