### ISSUE TITLE
关于videoavtar，想请教一下作者

### ISSUE THREAD

**Issue by SMY19999** [GAP-LAB-CUHK-SZ/REC-MV#22]

**Comment by SMY19999** [comment]
新年快乐！
我复现了videoavatar以及SelfRecon，并正在尝试复现REC-MV。
对于一个N帧的自旋转视频，videoavatar估计出的pose结果，是N×72。
72=24×3，代表SMPL的所有joint相对于父关节的旋转。
每个旋转用一个3D向量来表示，[x1, x2, x3]
我输入的视频是自旋转一周的，得到的root joint的结果大致变化如下：
![图片1](https://github.com/GAP-LAB-CUHK-SZ/REC-MV/assets/77394553/03b67004-59e2-439a-9c9b-0f66dc970c5d)
我很奇怪，这个估计结果的坐标系是和谁对齐的？
我测试了people-snap-shot的结果，姿态数据的变化趋势也和这个相似。
我想用其他算法来估计pose时，不知道该如何变换坐标系。
期待作者的回复~

**Comment by lifftel** [comment]
新年好呀，我不明白你的意思； 我最近在休假没看到邮件不好意思；
你用什么算法来估计pose，然后又是如何对其没对到呢？


________________________________
发件人: xiaoyang-RL9 ***@***.***>
发送时间: 2024年2月21日 16:02
收件人: GAP-LAB-CUHK-SZ/REC-MV ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [GAP-LAB-CUHK-SZ/REC-MV] 关于videoavtar，想请教一下作者 (Issue #22)


新年快乐！
我复现了videoavatar以及SelfRecon，并正在尝试复现REC-MV。
对于一个N帧的自旋转视频，videoavatar估计出的pose结果，是N×72。
72=24×3，代表SMPL的所有joint相对于父关节的旋转。
每个旋转用一个3D向量来表示，[x1, x2, x3]
我输入的视频是自旋转一周的，得到的root joint的结果大致变化如下：
1.png (view on web)<https://github.com/GAP-LAB-CUHK-SZ/REC-MV/assets/77394553/03b67004-59e2-439a-9c9b-0f66dc970c5d>
我很奇怪，这个估计结果的坐标系是和谁对齐的？
我测试了people-snap-shot的结果，姿态数据的变化趋势也和这个相似。
我想用其他算法来估计pose时，不知道该如何变换坐标系。
期待作者的回复~

―

**Comment by SMY19999** [comment]
感谢回复！
不好意思，是我搞错了。
在REC-MV的readme的[Preprocess Datasets](https://github.com/GAP-LAB-CUHK-SZ/REC-MV?tab=readme-ov-file#preprocess-datasets)节里，你提到了可以用[VideoAvatar](https://graphics.tu-bs.de/people-snapshot)来估计每个视频帧的SMPL参数。
我用[VIBE](https://github.com/mkocabas/VIBE)跑了一下，pose结果与[VideoAvatar](https://graphics.tu-bs.de/people-snapshot)相似。
