### ISSUE TITLE
Bool-long issue with tensors

### ISSUE THREAD

**Issue by albusdemens** [GAP-LAB-CUHK-SZ/REC-MV#3]
Great work! I am trying to run your demo code. https://github.com/GAP-LAB-CUHK-SZ/REC-MV/blob/77c3c08c9ad8197cc9da20ae51d63281b970208a/dataset/dataset.py#L353 --> I had to change this line to `body_parsing = body_parsing.long() ^ all_garment_parsing.long()`.

**Comment by lingtengqiu** [comment]
Thanks for your tips.
This may be caused by an issue with the version of Torch.
I will fix this bug to make it compatible with different versions of Torch.
