### ISSUE TITLE
Where is smpl_pytorch?

### ISSUE THREAD

**Issue by MinJunKang** [GAP-LAB-CUHK-SZ/REC-MV#5]
Hello, thanks for sharing the code.

I cannot find smpl_pytorch folder and when I run the demo code, I got the following error:

File "/workspace/NIPS23/HOIProject/REC-MV/model/Deformer.py", line 13, in <module>
    from smpl_pytorch.SMPL import SMPL,getSMPL
ImportError: cannot import name 'SMPL' from 'smpl_pytorch.SMPL' 

Can you help me?

**Comment by lingtengqiu** [comment]
I forget this folder. I will upload soon. Or you can find  the smpl_torch folder in SelfRecon: https://github.com/jby1993/SelfReconCode/tree/main/smpl_pytorch
