### ISSUE TITLE
scripts folder missing files?

### ISSUE THREAD

**Issue by merlinyx** [GAP-LAB-CUHK-SZ/REC-MV#6]
Hello! I was following the steps [here](https://github.com/GAP-LAB-CUHK-SZ/REC-MV#preprocess-your-dataset) to preprocess a video and I couldn't find the `openpose_predict.sh` file (and a couple other files). Could you maybe let me know where I could access them or if I should write these myself? If so, what are the desired outputs? Thanks!
And I'm just wondering if I just want to process on frame of a video, I can just keep one image in the folder `./female_large_pose/${video-name}/imgs/` and the rest will be the same? Thanks a lot!

**Comment by lingtengqiu** [comment]
Yes, the whole process of processing data is very long. For openpose, you must first configure the [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) and then give the results of openpose to [videoavatar](https://github.com/thmoa/videoavatars). The `openpose_predict.sh` is a script using to predict video 2D pose sequences, which is a prior for video avatar to obtain smpl sequences. Please following the tutorial written in Videoavatar.

For the second issues. Yes, you only need move the same data format into ./female_large_pose/${your-video}.

**Comment by lingtengqiu** [comment]
I will write a more detail tutorial to demonstrate how to process raw videos. Actually, the preprocess is definitely complex :(

**Comment by merlinyx** [comment]
I see, thank you for the explanations!

**Comment by merlinyx** [comment]
Hello! I have another quick question (which is a bit unrelated): if I want to generate a lower resolution garment mesh output, should I comment out the lines [here](https://github.com/GAP-LAB-CUHK-SZ/REC-MV/blob/main/engineer/networks/OptimGarmentNetwork.py#L2476-L2480)? Or is there a flag already for controlling the output resolution? Thank you!

**Comment by lingtengqiu** [comment]
see [here](https://github.com/GAP-LAB-CUHK-SZ/REC-MV/blob/main/engineer/networks/OptimGarmentNetwork.py#L2398C3-L2398C3), I control how resolution template mesh uses. 


> Hello! I have another quick question (which is a bit unrelated): if I want to generate a lower resolution garment mesh output, should I comment out the lines [here](https://github.com/GAP-LAB-CUHK-SZ/REC-MV/blob/main/engineer/networks/OptimGarmentNetwork.py#L2476-L2480)? Or is there a flag already for controlling the output resolution? Thank you!

**Comment by merlinyx** [comment]
Ah I see, thank you very much!

**Comment by merlinyx** [comment]
Hi! I wanted to follow up on the preprocessing; I tried following the steps detailed in the README.md and most of them went through just fine but I'm stuck at the videoavatars step1_pose.py. I think chumpy might have something incompatible with python 3 which caused strange errors that I cannot just fix based on the error messages. I just tried using python 2.7 but the environment setup itself ran into errors. Could you let me know which setup you used for running videoavatars to generate the pose sequence? Did you have to modify any chumpy source code? Thank you!

By the way, @lingtengqiu could you let me know your email address? I think I might have some further questions that would be easier if we can communicate through email! (the one from your homepage bounces back for me) Thanks!
