### ISSUE TITLE
How can I reproduce the eval results

### ISSUE THREAD

**Issue by MingiYeom** [GAP-LAB-CUHK-SZ/REC-MV#9]
Thank you for sharing an excellent paper, REC-MV.

I want to reproduce it like Table 1.
There are 4 data, Female 1, Female 3, Male 1, and Male 2.
However, in the data SelfRecon(PeopleSnapshot), there are many Female 3(casual, sport), Male 1(casual, plaza, sport), and Male 2(causal, outdoor, plaza, sport).
Therefore, could I know which datasets are used for evaluation and is there a simple way to reproduce the quantitative result(code and ground-truth garment mesh etc.)?

**Comment by lifftel** [comment]
Hi, Mingi.

The Female1, Female3, Male1, Male2 are the synthetic dataset produced by SelfRecon. For Female 3(casual, sport), Male 1(casual, plaza, sport), and Male 2(causal, outdoor, plaza, sport), there are the items from People Snapshot. You could obtain their Synthetic data  from https://mailustceducn-my.sharepoint.com/personal/jby1993_mail_ustc_edu_cn/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fjby1993%5Fmail%5Fustc%5Fedu%5Fcn%2FDocuments%2FSelfReconData%2FSynthetic.
________________________________
发件人: Mingi Yeom ***@***.***>
发送时间: 2023年7月18日 18:35
收件人: GAP-LAB-CUHK-SZ/REC-MV ***@***.***>
抄送: Subscribed ***@***.***>
主题: [GAP-LAB-CUHK-SZ/REC-MV] How can I reproduce the eval results (Issue #9)


Thank you for sharing an excellent paper, REC-MV.

I want to reproduce it like Table 1.
There are 4 data, Female 1, Female 3, Male 1, and Male 2.
However, in the data SelfRecon[1], there are many Female 3(casual, sport), Male 1(casual, plaza, sport), and Male 2(causal, outdoor, plaza, sport).
Therefore, could I know which datasets are used for evaluation and is there a simple way to reproduce the quantitative result?

―

**Comment by lingtengqiu** [comment]
Hi, Mingi.

The Female1, Female3, Male1, Male2 are the synthetic dataset produced by SelfRecon. For Female 3(casual, sport), Male 1(casual, plaza, sport), and Male 2(causal, outdoor, plaza, sport), there are the items from People Snapshot. You could obtain their Synthetic data  from the following [link](https://mailustceducn-my.sharepoint.com/personal/jby1993_mail_ustc_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjby1993%5Fmail%5Fustc%5Fedu%5Fcn%2FDocuments%2FSelfReconData&ga=1)

**Comment by lingtengqiu** [comment]
We parse gt garments from SelfRecon synthetic dataset as GT mesh. Then, we could compute metric from both predict garment mesh in canonical space and GT mesh.

**Comment by SMY19999** [comment]
Hi, Lingteng.

I note that in REC-MV, you show the garment-only mesh of the dataset from SelfRecon. 

You say "We parse gt garments from SelfRecon synthetic dataset as GT mesh."

What method do you use to extract the garment mesh?

Thanks a lot!

> We parse gt garments from SelfRecon synthetic dataset as GT mesh. Then, we could compute metric from both predict garment mesh in canonical space and GT mesh.
